[build]
  command = "npm run build"
  publish = "build/"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[build.environment]
  NODE_PATH = "src/"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = true
  conditions = {Language: "en"}
